server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

#mongoHost : "localhost"
#mongoPort : 27017
#mongoDB : notification_db
#collectionName: event



